### ISSUE TITLE
Japanese texts for morse training

### ISSUE THREAD

**Issue by Luci6fuge** [dj1yfk/lcwo#1]
Hello Fabian.

I am preparing Japanese texts for morse training.
https://gist.github.com/Luci6fuge/2385de2000b0a751e460a6322d71750e
Would you mind adding them to your database?

**Comment by dj1yfk** [comment]
Done!

https://git.fkurz.net/dj1yfk/lcwo/commit/03543c07799e79fa537b8c6748deb1931889a250
